//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWEB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public int ID { get; set; }
        public Nullable<int> ContactoDeVisita { get; set; }
        public string NombreCompleto { get; set; }
        public string Motivo { get; set; }
        public string Fecha { get; set; }
        public string HoraEntrada { get; set; }
        public string HoraSalida { get; set; }
    
        public virtual CONTACTOS CONTACTOS { get; set; }
    }
}
